volumes:
  chromadb:
  minio:
  postgres:
  mongodb:
  sadtalker_data:
  voice_clone_data:

networks:
  multidimension:
    driver: bridge
    
services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chromadb:/chroma/.chroma/index
    ports:
      - ${CHROMADB__PORT}:8000
    networks:
      - multidimension

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "9510:4000"
    networks:
      - multidimension
    volumes:
      - ./config.yaml:/app/config.yaml
    command:
      - "--config=/app/config.yaml"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  minio:
    image: quay.io/minio/minio
    ports:
      - ${MINIO__HTTP_PORT}:9000
      - ${MINIO__GUI_PORT}:9001
    networks:
      - multidimension
    volumes:
      - ./minio:/data
    environment:
      - MINIO_ROOT_USER=${MINIO__ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO__SECRET_KEY}

    command: server --console-address ":9001" /data

  postgres:
    image: postgres:17.0-alpine
    ports:
      - ${POSTGRES__PORT}:5432
    networks:
      - multidimension
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES__USER}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_DB=${POSTGRES__DB}

  mongodb:
    image: mongo:7.0.23
    ports:
      - ${MONGO__PORT}:27017
    networks:
      - multidimension
    volumes:
      - mongodb:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO__USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO__PASSWORD}

  mongo-gui:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - multidimension
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO__HOST}
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO__USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO__PASSWORD}

  rag_service:
    build:
      context: .
      dockerfile: dockers/Dockerfile
      args:
        - PYTHON_VERSION=python3.11
        - PACKAGE=rag_service
        - OPTIONAL_BUILD=src/rag_service/__init__.py
    ports:
      - "3005:3005"
    networks:
      - multidimension
    command: uv run rag_service
    depends_on:
      - chromadb
    volumes:
      - type: bind
        source: ./services/rag_service
        target: /home/reunion/app/services/rag_service
      - type: bind
        source: ./libs/
        target: /home/reunion/app/libs/
    environment:
      - CHROMADB__HOST=${CHROMADB__HOST}
      - CHROMADB__PORT=${CHROMADB__PORT}

  chat_service:
    build:
      context: .
      dockerfile: dockers/Dockerfile
      args:
        - PYTHON_VERSION=python3.11
        - PACKAGE=chat_service
        - OPTIONAL_BUILD=src/chat_service/__init__.py
  
    ports:
      - 3000:3000
    
    networks:
      - multidimension
    command: uv run chat_service

    volumes:
      - type: bind
        source: ./services/chat_service
        target: /home/reunion/app/services/chat_service
      - type: bind
        source: ./libs/
        target: /home/reunion/app/libs/

    environment:
      - LLM__OPENAI_KEY=${LLM__OPENAI_KEY}
      - RAG_SERVICE_URL=${RAG_SERVICE_URL}

  identity_service:
    build:
      context: .
      dockerfile: dockers/Dockerfile
      args:
        - PYTHON_VERSION=python3.11
        - PACKAGE=identity_service
        - OPTIONAL_BUILD=src/identity_service/__init__.py
    ports:
      - "8762:8762"
    networks:
      - multidimension
    command: uv run identity_service
    volumes:
      - type: bind
        source: ./services/identity_service
        target: /home/reunion/app/services/identity_service
      - type: bind
        source: ./libs/
        target: /home/reunion/app/libs/
    environment:
      - FRONTEND_HOST=${FRONTEND_HOST}
      - PROJECT_NAME=${PROJECT_NAME}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - ACCESS_TOKEN_SECRET_KEY=${ACCESS_TOKEN_SECRET_KEY}
      - RESET_PASSWORD_SECRET_KEY=${RESET_PASSWORD_SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - SMTP_TLS=${SMTP_TLS}
      - SMTP_SSL=${SMTP_SSL}
      - SMTP_PORT=${SMTP_PORT}
      - POSTGRES_SETTINGS__USER=${POSTGRES__USER}
      - POSTGRES_SETTINGS__PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_SETTINGS__HOST=${POSTGRES__HOST}
      - POSTGRES_SETTINGS__PORT=${POSTGRES__PORT}
      - POSTGRES_SETTINGS__DB=${POSTGRES__DB}

  livetalking:
    build:
      context: .
      dockerfile: dockers/Dockerfile.livetalking
      args:
        - PYTHON_VERSION=python3.11
        - PACKAGE=livetalking
        - OPTIONAL_BUILD=src/livetalking/__init__.py
        - APT_PACKAGE=git gcc libpq-dev libgl1 libglib2.0-0
  
    ports:
      - 8010:8010
    
    networks:
      - multidimension
    command: uv run livetalking

    volumes:
      - type: bind
        source: ./services/livetalking
        target: /home/reunion/app/services/livetalking
      - type: bind
        source: ./libs/
        target: /home/reunion/app/libs/
      - ./data:/home/reunion/app/data

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - LLM__OPENAI_KEY=${LLM__OPENAI_KEY}
      - LLM__MODEL_NAME=${LLM__MODEL_NAME}
      - LIPREAL__XTTS__REF_FILE=${LIPREAL__XTTS__REF_FILE}
      - LIPREAL__XTTS__TTS_SERVER=${LIPREAL__XTTS__TTS_SERVER}
      - MINIO__ACCESS_KEY=${MINIO__ACCESS_KEY}
      - MINIO__SECRET_KEY=${MINIO__SECRET_KEY}
      - MINIO__HOST=${MINIO__HOST}
      - MINIO__HTTP_PORT=${MINIO__HTTP_PORT}

  sadtalker:
    build:
      context: .
      dockerfile: dockers/Dockerfile.sadtalker

    ports:
      - "3636:3636"
    
    networks:
      - multidimension
    command: uvicorn main:app --host 0.0.0.0 --port 3636 --reload

    volumes:
      - type: bind
        source: ./services/sadtalker
        target: /home/reunion/app/services/sadtalker
      - type: bind
        source: ./libs/
        target: /home/reunion/app/libs/
      - ./sadtalker_data:/sadtalker/results

    environment:
      - MINIO__ACCESS_KEY=${MINIO__ACCESS_KEY}
      - MINIO__SECRET_KEY=${MINIO__SECRET_KEY}
      - MINIO__HOST=${MINIO__HOST}
      - MINIO__HTTP_PORT=${MINIO__HTTP_PORT}

    depends_on:
      - minio
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  wav2lip:
    build:
      context: .
      dockerfile: dockers/Dockerfile
      args:
          - PYTHON_VERSION=python3.11
          - PACKAGE=wav2lip
          - OPTIONAL_BUILD=src/wav2lip/__init__.py
          - APT_PACKAGE=git gcc libpq-dev libgl1 libglib2.0-0
    ports:
      - "8020:8020"
    networks:
      - multidimension
    command: uv run wav2lip
    volumes:
      - type: bind
        source: ./services/wav2lip
        target: /home/reunion/app/services/wav2lip
      - type: bind
        source: ./libs/
        target: /home/reunion/app/libs/
      - ./wav2lip_data:/home/reunion/app/wav2lip_data
    environment:
      - MINIO__ACCESS_KEY=${MINIO__ACCESS_KEY}
      - MINIO__SECRET_KEY=${MINIO__SECRET_KEY}
      - MINIO__HOST=${MINIO__HOST}
      - MINIO__HTTP_PORT=${MINIO__HTTP_PORT}
    depends_on:
      - minio
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
  voice_clone:
    build:
      context: .
      dockerfile: dockers/Dockerfile.voice_clone

    ports:
      - "8002:8002"
    
    networks:
      - multidimension
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - type: bind
        source: ./services/voice_clone
        target: /home/reunion/app/services/voice_clone
      - ./voice_clone_data:/voice_clone/results

    environment:
      - MINIO__ACCESS_KEY=${MINIO__ACCESS_KEY}
      - MINIO__SECRET_KEY=${MINIO__SECRET_KEY}
      - MINIO__HOST=${MINIO__HOST}
      - MINIO__HTTP_PORT=${MINIO__HTTP_PORT}

    depends_on:
      - minio

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  character_service:
    build:
      context: .
      dockerfile: dockers/Dockerfile
      args:
        - PYTHON_VERSION=python3.11
        - PACKAGE=character_service
        - OPTIONAL_BUILD=src/character_service/__init__.py

    ports:
      - "3006:3006"

    depends_on:
      - mongodb
    
    networks:
      - multidimension
    command: uv run character_service

    volumes:
      - type: bind
        source: ./services/character_service
        target: /home/reunion/app/services/character_service
      - type: bind
        source: ./libs/
        target: /home/reunion/app/libs/
    environment:
      - MONGODB__HOST=${MONGO__HOST}
      - MONGODB__PORT=27017
      - MONGODB__USER=${MONGO__USER}
      - MONGODB__PASSWORD=${MONGO__PASSWORD}
      - MONGODB__DB=${MONGO__DB}

  frontend:
    build:
      context: .
      dockerfile: dockers/Dockerfile.frontend

    volumes:
      - type: bind
        source: ./web
        target: /usr/share/nginx/html
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - multidimension

    container_name: frontend
    ports:
      - "8080:80"

  indexer:
    build:
      context: .
      dockerfile: dockers/Dockerfile
      args:
        - PYTHON_VERSION=python3.11
        - PACKAGE=indexer
        - OPTIONAL_BUILD=src/indexer/__init__.py
    ports:
      - "3036:3036"
    volumes:
      - type: bind
        source: ./services/indexer
        target: /home/reunion/app/services/indexer
      - type: bind
        source: ./libs/
        target: /home/reunion/app/libs/
    networks:
      - multidimension
    command: uv run indexer
    depends_on:
      - minio
      - mongodb
      - chromadb
      - sadtalker
      - wav2lip
      - litellm
    environment:
      - MINIO__ACCESS_KEY=${MINIO__ACCESS_KEY}
      - MINIO__SECRET_KEY=${MINIO__SECRET_KEY}
      - MINIO__HOST=${MINIO__HOST}
      - MINIO__HTTP_PORT=${MINIO__HTTP_PORT}
      - MINIO_ROOT_USER=${MINIO__ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO__SECRET_KEY}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO__USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO__PASSWORD}
      - MONGO__USER=${MONGO__USER}
      - MONGO__PASSWORD=${MONGO__PASSWORD}
      - MONGO__DB=${MONGO__DB}
      - MONGO__HOST=${MONGO__HOST}
      - MONGO__PORT=27017
      - CHROMADB__HOST=${CHROMADB__HOST}
      - CHROMADB__PORT=${CHROMADB__PORT}
      - LITELLM__MODEL=${LITELLM__MODEL}
      - LITELLM__URL=${LITELLM__URL}
      - LITELLM__EMBEDDING_MODEL=${LITELLM__EMBEDDING_MODEL}