events {}

http {
    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index webrtcapi.html;   # đổi từ index.html -> webrtcapi.html

        location / {
            try_files $uri /webrtcapi.html;
        }

        # Proxy API requests to FastAPI backend
        location /v1/ {
            proxy_pass http://livetalking:8010;   # đổi backend -> livetalking
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
