[project]
name = "fs-livetalking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.uv.workspace]
members = [
    "services/rag_service",
    "services/chat_service",
    "libs/chromadb_client",
    "services/indexer",
    "libs/base",
    "libs/logger",
    "libs/llm_client",
    "libs/text_to_speech",
    "libs/realistic",
    "libs/asr",
    "services/livetalking",
    "libs/humanplayer",
    "libs/minio_client",
    "libs/postgresql_client",
    "libs/mongo_client", 
    "services/wav2lip", 
    "services/character_service",
    "services/identity_service",
    "libs/authorization",
]

[tool.uv.sources]
chat-service = { workspace = true }
rag-service = { workspace = true }
logger = { workspace = true }
base = { workspace = true }
livetalking = { workspace = true }
realistic = { workspace = true }
text-to-speech = { workspace = true }
indexer = { workspace = true }
