[project]
name = "minio-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "HoangManhh", email = "144936790+HoangManhh@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = [
    "base",
    "logger",
    "minio>=7.2.16",
    "pydantic>=2.8.2",
]

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
base = { workspace = true }
logger = { workspace = true }
