[project]
name = "rag-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "huskywannacry", email = "ttkien1503@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "asgi-correlation-id>=4.3.4",
    "base",
    "chromadb-client",
    "fastapi>=0.116.1",
    "logger",
    "pydantic-settings>=2.10.1",
    "uvicorn>=0.35.0",
]

[project.scripts]
rag_service = "rag_service:main"

[build-system]
requires = ["uv_build>=0.8.7,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
logger = { workspace = true }
base = { workspace = true }
chromadb-client = { workspace = true }

