model: 'services/livetalking/src/livetalking/shared/models/wav2lip.pth'
bucket_name: 'reunion'
max_session: 10

lipreal:
  W: 450
  H: 450
  fps: 20
  idx: 0
  batch_size: 16
  model: 'wav2lip'
  customopt: []
  customvideo_config: ''