FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    wget \
    curl \
    ffmpeg \
    ca-certificates \
    bzip2 \
    build-essential \
    portaudio19-dev \
    python3-pip \
    python3-dev \ 
    libgl1-mesa-glx libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir torch==2.1.1+cu118 torchaudio==2.1.1+cu118 --index-url https://download.pytorch.org/whl/cu118

COPY /services/voice_clone/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY services/voice_clone voice_clone

WORKDIR /voice_clone

