"""Add soft delete to tbl_user

Revision ID: 438f9c26f378
Revises: 12c0ddd11f65
Create Date: 2025-12-18 11:12:58.655004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '438f9c26f378'
down_revision: Union[str, None] = '12c0ddd11f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index('uq_user_email', 'user', ['email'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('uq_user_username', 'user', ['username'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_username', table_name='user', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('uq_user_email', table_name='user', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_column('user', 'is_deleted')
    # ### end Alembic commands ###
